### ISSUE TITLE
Another tool: sixer

### ISSUE THREAD

**Issue by vstinner** [fedora-python/portingguide#3]
Hi,

I wrote a tool to port OpenStack to Python 3: http://pypi.python.org/pypi/sixer

You may mention it in your guide :-)

**Comment by vstinner** [comment]
Are you interested to mention my tool sixer?

**Comment by encukou** [comment]
Hello,
Sorry for the delay, the guide was on the back-burner for now.

The guide explicitly tries to list as few alternatives as possible: a list of tools to try is much less useful than clear instructions to follow and important things to understand (even if there are slightly better tools for some of the tasks).
For that reason, I'm not convinced to list sixer, which stil strikes me as too tied to the OpenStack code style.
I might be wrong though – I haven't used it on any significant code base. Is there some area where it really shines in comparison with modernize?

**Comment by vstinner** [comment]
> The guide explicitly tries to list as few alternatives as possible

Ok, I see and I understand, no problem. I close the issue.

I don't know well modernize, it seems similar to sixer. Maybe more reliable since it uses lib2to3, which is more reliable than regular expressions used by sixer.

About OpenStack coding style: the main part specific to OpenStack is the way to organize Python imports. I agree that there is no option right now to choose how imports are grouped and sorted.
