### ISSUE TITLE
argparse incompatible change

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingguide#39]
As with https://github.com/fedora-python/portingguide/issues/38, there is one particular unfortunate argparse incompatible change that we might want to describe in etc.

https://pagure.io/fedpkg/c/4ee70510
https://bugs.launchpad.net/cloud-init/+bug/1424277

**Comment by encukou** [comment]
https://github.com/fedora-python/portingguide/pull/70 adds a note about changes that aren't covered in the guide.
