### ISSUE TITLE
Minor sentence change

### ISSUE THREAD

**Issue by ASC95** [fedora-python/portingguide#57]
Recommend changing this sentence in core-obj-misc.rst:
**Old:**
Python 2 had two kinds of methods: bound methods, which you could retreive from a class object, and unbound methods, which were retreived from an instance:
**New:**
Python 2 had two kinds of methods: bound methods, which you could retrieve from an instance of a class, and unbound methods, which were retrieved from a class:

**Comment by encukou** [comment]
Finally got around to it.
Thanks for the report!
