### ISSUE TITLE
Python 3.9 incompatible changes

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingguide#59]
> open(), io.open(), codecs.open() and fileinput.FileInput no longer accept 'U' (“universal newline”) in the file mode. This flag was deprecated since Python 3.3. In Python 3, the “universal newline” is used by default when a file is open in text mode. The newline parameter of open() controls how universal newlines works. (Contributed by Victor Stinner in bpo-37330.)

> array.array: tostring() and fromstring() methods have been removed. They were aliases to tobytes() and frombytes(), deprecated since Python 3.2. (Contributed by Victor Stinner in bpo-38916.)

> The abstract base classes in collections.abc no longer are exposed in the regular collections module. This will help create a clearer distinction between the concrete classes and the abstract base classes.

We should document those eventually as incompatibilities between 2 and 3.

**Comment by encukou** [comment]
#70 adds a note about changes that aren't covered in the guide.
