### ISSUE TITLE
Lack of copyright status

### ISSUE THREAD

**Issue by raionik** [fedora-python/portingguide#62]
Hello,

I wonder about the copyright status or license information about this book. 
I think a license file in the root directory will help.
Thank you in advance.

**Comment by encukou** [comment]
Oh dear, it looks like I forgot to add the licence when I started :(

Dear contributors, is it OK to release your contributions to this guide under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) for the text and [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) (“no rights reserved”) for all code (mainly code samples within the text, but also the tests & build scripts)?

* [x]  @encukou (me)
* [x]  @hroncok
* [x]  @frenzymadness
* [x]  `ciphergoth` (typo fixes)
* [x]  @sallner – ed46a5a
* [x]  @cclauss – 61f2e43
* [x]  `alexwlchan` (typo fix)
* [x]  `stratakis` (typo fix)
* [x]  `irushchyshyn` (typo fixes)
* [x]  `jefftrull` (trivial fix)
* [x]  `mikestange` (typo fixes)
* [x]  `ncoghlan` (trivial fix)
* [x]  `kratz00` (typo fix)
* [x]  @torsava
* [x]  `treyhunner` (trivial fix)
* [x]  `doerwalter` (typo fix)

(I tried to filter out contributions that look not copyrightable, so I don't spam too many people. But even the typo fixes are appreciated!)

**Comment by cclauss** [comment]
I agree to CC-BY-SA 4.0 and CC-0 for my changes.

**Comment by sallner** [comment]
I agree to the CC-BY-SA 4.0 and CC-0 for my change.

**Comment by frenzymadness** [comment]
It seems we have all agreed.

**Comment by encukou** [comment]
Added. Thank you, everyone!

**Comment by raionik** [comment]
thank you all
